#!/bin/bash
start_time=`date +%s`

### bash hints
### 2>&1                        redirect stderr to stdout
### | tee -a log.log            screen outputs also append to log file
### ; ( exit ${PIPESTATUS} )    correct program exitting status
### Only run parallel when you're sure that there are no errors.

cd /home/wangq/data/rna-seq/mouse_trans

### bowtie index
# bowtie2-build /home/wangq/data/rna-seq/mouse_trans/ref/mouse.65.fa /home/wangq/data/rna-seq/mouse_trans/ref/mouse.65

cd /home/wangq/data/rna-seq/mouse_trans/process

#----------------------------#
# cuffdiff_cxb
#----------------------------#
echo "* Start cuffnorm `date`" | tee -a /home/wangq/data/rna-seq/mouse_trans/log/cuffmergediff.log

/home/wangq/bin/cuffnorm -p 14 \
    --no-update-check \
    /home/wangq/data/rna-seq/mouse_trans/process/merged_asm/merged.gtf \
    -L Adrenal,Colon,Duodenum,GenitalFatPad,Heart,Kidney,LgIntestine,Liver,Lung,MammaryGland,Ovary,SmIntestine,Spleen,Stomach,SubcFatPad,Testis,Thymus \
    /home/wangq/data/rna-seq/mouse_trans/process/Adrenal/SRR453116/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Adrenal/SRR453117/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Adrenal/SRR453118/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Adrenal/SRR453119/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Adrenal/SRR453120/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Adrenal/SRR453121/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/Colon/SRR453166/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Colon/SRR453167/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Colon/SRR453168/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Colon/SRR453169/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Colon/SRR453170/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Colon/SRR453171/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/Duodenum/SRR453109/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Duodenum/SRR453110/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Duodenum/SRR453111/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Duodenum/SRR453112/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Duodenum/SRR453113/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Duodenum/SRR453114/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Duodenum/SRR453115/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/GenitalFatPad/SRR453126/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/GenitalFatPad/SRR453127/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/GenitalFatPad/SRR453128/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/GenitalFatPad/SRR453129/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/Heart/SRR453172/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Heart/SRR453173/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Heart/SRR453174/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Heart/SRR453175/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/Kidney/SRR453144/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Kidney/SRR453145/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Kidney/SRR453146/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Kidney/SRR453147/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Kidney/SRR453148/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Kidney/SRR453149/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/LgIntestine/SRR453122/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/LgIntestine/SRR453123/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/LgIntestine/SRR453124/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/LgIntestine/SRR453125/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/Liver/SRR453150/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Liver/SRR453151/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Liver/SRR453152/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Liver/SRR453153/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Liver/SRR453154/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Liver/SRR453155/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/Lung/SRR453156/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Lung/SRR453157/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Lung/SRR453158/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Lung/SRR453159/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/MammaryGland/SRR453087/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/MammaryGland/SRR453088/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/MammaryGland/SRR453089/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/MammaryGland/SRR453090/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/MammaryGland/SRR453091/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/MammaryGland/SRR453092/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/Ovary/SRR453077/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Ovary/SRR453078/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Ovary/SRR453079/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Ovary/SRR453080/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Ovary/SRR453081/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Ovary/SRR453082/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Ovary/SRR453083/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Ovary/SRR453084/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Ovary/SRR453085/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Ovary/SRR453086/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/SmIntestine/SRR453099/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/SmIntestine/SRR453100/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/SmIntestine/SRR453101/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/SmIntestine/SRR453102/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/SmIntestine/SRR453103/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/SmIntestine/SRR453104/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/SmIntestine/SRR453105/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/SmIntestine/SRR453106/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/SmIntestine/SRR453107/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/SmIntestine/SRR453108/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/Spleen/SRR453160/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Spleen/SRR453161/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Spleen/SRR453162/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Spleen/SRR453163/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Spleen/SRR453164/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Spleen/SRR453165/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/Stomach/SRR453093/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Stomach/SRR453094/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Stomach/SRR453095/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Stomach/SRR453096/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Stomach/SRR453097/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Stomach/SRR453098/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/SubcFatPad/SRR453130/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/SubcFatPad/SRR453131/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/SubcFatPad/SRR453132/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/SubcFatPad/SRR453133/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/Testis/SRR453140/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Testis/SRR453141/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Testis/SRR453142/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Testis/SRR453143/cq_out/abundances.cxb \
    /home/wangq/data/rna-seq/mouse_trans/process/Thymus/SRR453134/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Thymus/SRR453135/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Thymus/SRR453136/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Thymus/SRR453137/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Thymus/SRR453138/cq_out/abundances.cxb,/home/wangq/data/rna-seq/mouse_trans/process/Thymus/SRR453139/cq_out/abundances.cxb \
    -o /home/wangq/data/rna-seq/mouse_trans/process/norm_out

[ $? -ne 0 ] && echo `date` ] [cuffnorm] failed >> /home/wangq/data/rna-seq/mouse_trans/fail.log && exit 255
echo "* End cuffnorm `date`" | tee -a /home/wangq/data/rna-seq/mouse_trans/log/cuffmergediff.log

